security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_CONSULTANT, ROLE_ALLOWED_TO_SWITCHED ]
        ROLE_CONSULTANT: [ ROLE_USER, ROLE_CONSULTANT ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
          lazy: true
          provider: app_user_provider
          custom_authenticator: App\Security\AppAuthenticator
          logout:
            path: app_logout
          remember_me:
            secret: '%kernel.secret%' # required
            lifetime: 604800

    access_control:
      - { path: ^/admin, roles: ROLE_CONSULTANT }


when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
